# Service configuration for service03
# Generated on Sat Aug 23 09:11:04 CEST 2025

service_name: service03
service_type: nodejs
runtime_variant: bun
vm_name: service03
vm_id: 100
vm_cores: 2
vm_memory: 2048
vm_disk_size: 20
vm_storage: local-lvm
vm_network_bridge: vmbr0
vm_swap: 512
vm_unprivileged: true

app_name: service03
app_user: appuser
app_dir: /opt/service03
app_service_name: service03
app_port: 3008
app_main_file: index.js
local_app_path: "../../services/service03"

service_hostname: service03
app_subdomain: 

dns_server: 192.168.1.11
dns_domain: proxmox.local

# Proxmox node override (leave empty to use global default)
proxmox_node: pve

# Service type specific configuration
nodejs_runtime: bun

# Custom environment variables
custom_env_vars: {}

# Additional ports to open in firewall
additional_ports: []
