# Python Service Type Configuration
service_type: python
runtime_name: "Python"

# Runtime installation tasks
runtime_install:
  - name: "Install Python runtime"
    apt:
      name:
        - python3
        - python3-pip
        - python3-venv
      state: present

# Dependency installation
dependency_install:
  - name: "Create Python virtual environment"
    shell: python3 -m venv venv
    args:
      chdir: "{{ app_dir }}"
      creates: "{{ app_dir }}/venv"
    become_user: "{{ app_user }}"
  
  - name: "Install Python dependencies"
    shell: |
      source venv/bin/activate
      pip install -r requirements.txt
    args:
      chdir: "{{ app_dir }}"
    become_user: "{{ app_user }}"
    when: requirements_file_exists.stat.exists
  
  - name: "Check if requirements.txt exists"
    stat:
      path: "{{ app_dir }}/requirements.txt"
    register: requirements_file_exists

# File exclusions for tar archive
file_exclusions:
  - "__pycache__"
  - "*.pyc"
  - ".git"
  - "deployment"
  - "deployments"
  - "*.log"
  - ".env"
  - "venv"
  - ".pytest_cache"

# Default environment variables
default_env:
  PYTHONPATH: "{{ app_dir }}"
  PYTHONUNBUFFERED: "1"

# Health check endpoint
health_check_path: "/health"

# Default systemd service configuration
systemd_service:
  Type: simple
  ExecStart: "{{ app_dir }}/venv/bin/python {{ app_main_file | default('main.py') }}"
  Restart: always
  RestartSec: 10
