# Python Service Type Configuration
service_type: python
runtime_name: "Python"

# Template parts provided by this service type
provides_runtime_install: true
provides_dependency_install: true
provides_build_tasks: false
provides_systemd_service: true

# File exclusions for tar archive
file_exclusions:
  - "__pycache__"
  - "*.pyc"
  - ".git"
  - "deployment"
  - "deployments"
  - "*.log"
  - ".env"
  - "venv"
  - ".pytest_cache"

# Default environment variables
default_env:
  PYTHONPATH: "{{ app_dir }}"
  PYTHONUNBUFFERED: "1"

# Health check endpoint
health_check_path: "/health"
