# Node.js/Bun.js Service Type Configuration
service_type: nodejs
runtime_name: "Node.js/Bun.js"

# Template parts provided by this service type
provides_runtime_install: true
provides_dependency_install: true
provides_build_tasks: true
provides_systemd_service: true
provides_redeploy_tasks: true
provides_health_check: true

# File exclusions for tar archive
file_exclusions:
  - "node_modules"
  - ".git"
  - "deployment"
  - "deployments"
  - "*.log"
  - ".env"
  - ".npm"
  - "package-lock.json"

# Default environment variables
default_env:
  NODE_ENV: production
  HOST: "0.0.0.0"

# Health check endpoint
health_check_path: "/health"
