# Signal CLI REST API Service Type Configuration
service_type: signal-api
runtime_name: "Signal CLI REST API"

# Runtime installation tasks
runtime_install:
  - name: "Install Java runtime"
    apt:
      name:
        - "openjdk-17-jdk"
        - "openjdk-17-jre"
      state: present
  
  - name: "Install Go runtime"
    shell: |
      cd /tmp
      wget https://go.dev/dl/go1.21.0.linux-amd64.tar.gz
      tar -C /usr/local -xzf go1.21.0.linux-amd64.tar.gz
      ln -sf /usr/local/go/bin/go /usr/local/bin/go
    args:
      creates: /usr/local/bin/go

# Dependency installation
dependency_install:
  - name: "Download and setup Signal CLI"
    shell: |
      cd /tmp
      wget https://github.com/AsamK/signal-cli/releases/download/v0.13.5/signal-cli-0.13.5.tar.gz
      tar -C /opt -xzf signal-cli-0.13.5.tar.gz
      ln -sf /opt/signal-cli-0.13.5/bin/signal-cli /usr/local/bin/signal-cli
    args:
      creates: /usr/local/bin/signal-cli
  
  - name: "Clone and build Signal CLI REST API"
    shell: |
      export PATH=$PATH:/usr/local/go/bin
      git clone https://github.com/bbernhard/signal-cli-rest-api.git .
      go mod download
      go build -o {{ app_service_name }} ./src
    args:
      chdir: "{{ app_dir }}"
    become_user: "{{ app_user }}"
    environment:
      GOOS: linux
      GOARCH: amd64

# Template parts provided by this service type
provides_runtime_install: true
provides_dependency_install: true
provides_build_tasks: false
provides_systemd_service: true
provides_redeploy_tasks: true
provides_health_check: true

# File exclusions for tar archive
file_exclusions:
  - ".git"
  - "deployment"
  - "deployments"
  - "*.log"
  - ".env"
  - "vendor"
  - "*.exe"
  - "signal-cli-config"
  - "data"
  - "tmp"

# Default environment variables
default_env:
  MODE: "normal"  # Options: normal, native, json-rpc
  PORT: "8080"
  SIGNAL_CLI_CONFIG_DIR: "/opt/signal-api/data"
  LOG_LEVEL: "info"
  AUTO_RECEIVE_SCHEDULE: ""  # Cron format, e.g. "0 22 * * *"

# Health check endpoint
health_check_path: "/v1/health"

# Default systemd service configuration
systemd_service:
  Type: simple
  ExecStart: "{{ app_dir }}/{{ app_service_name }}"
  Restart: always
  RestartSec: 10
  Environment: "SIGNAL_CLI_CONFIG_DIR=/opt/signal-api/data"
  WorkingDirectory: "{{ app_dir }}"

# Signal-specific configuration
signal_cli_version: "0.13.5"  # Latest stable version
graalvm_version: "22.3.0"     # For native compilation
java_version: "17"            # Required Java version

# Repository configuration for deployment and redeployment
signal_api_repo: "https://github.com/bbernhard/signal-cli-rest-api.git"
signal_api_version: "HEAD"    # Can be overridden in service-config.yml to specify commit/tag
