---
# Ansible Galaxy requirements for Proxmox deployment
collections:
  - name: community.general
    version: ">=6.0.0"
  - name: community.crypto
    version: ">=2.0.0"
  - name: ansible.posix
    version: ">=1.0.0"
