# Service configuration for go-api
# Generated on Wed Aug 20 09:17:22 CEST 2025

service_name: go-api
vm_name: go-api
vm_id: 212
vm_cores: 2
vm_memory: 2048
vm_disk_size: 20
vm_storage: local-lvm
vm_network_bridge: vmbr0
vm_swap: 512
vm_unprivileged: true

app_name: go-api
app_user: appuser
app_dir: /opt/go-api
app_service_name: go-api
app_port: 8080
local_app_path: "../../services/go-api"

service_hostname: go-api
app_subdomain: go-api

dns_server: 192.168.1.11
dns_domain: proxmox.local

# Custom environment variables (add as needed)
custom_env_vars: {}

# Additional ports to open in firewall (add as needed)
additional_ports: []
