# Service configuration for postgres-db
# Generated on Fri Aug 22 17:05:48 CEST 2025

service_name: postgres-db
service_type: database
runtime_variant: postgresql
vm_name: postgres-db
vm_id: 220
vm_cores: 2
vm_memory: 2048
vm_disk_size: 20
vm_storage: local-lvm
vm_network_bridge: vmbr0
vm_swap: 512
vm_unprivileged: true

app_name: postgres-db
app_user: appuser
app_dir: /opt/postgres-db
app_service_name: postgres-db
app_port: 5432
app_main_file: 
local_app_path: "../../services/postgres-db"

service_hostname: postgres-db
app_subdomain: 

dns_server: 192.168.1.11
dns_domain: proxmox.local

# Proxmox node override (leave empty to use global default)
# proxmox_node: pve2

# Service type specific configuration
db_type: postgresql
db_name: postgres-db
db_user: postgres-db
db_password: hdqsj6SxuYRBUZXwdXySKBmEvXElytMZwMJgyVxS0j0=

# Custom environment variables
custom_env_vars: {}

# Additional ports to open in firewall
additional_ports: []
