---
# Service-specific variables for db-test
# Database service type group vars

# Proxmox Configuration
proxmox_host: "{{ lookup('env', 'PROXMOX_HOST') | default('192.168.1.100') }}"
proxmox_user: "{{ lookup('env', 'PROXMOX_USER') | default('root@pam') }}"
proxmox_password: "{{ lookup('env', 'PROXMOX_PASSWORD') }}"
proxmox_node: "{{ proxmox_node_override | default(lookup('env', 'PROXMOX_NODE')) | default('proxmox') }}"
proxmox_api_validate_certs: false

# Proxmox API Token Authentication (preferred for automation)
proxmox_token_id: "{{ lookup('env', 'TOKEN_ID') | default('') }}"
proxmox_token_secret: "{{ lookup('env', 'TOKEN_SECRET') | default('') }}"

# Service-specific configuration
service_name: db-test
vm_name: db-test
vm_id: 550
vm_cores: 2
vm_memory: 2048  # MB
vm_disk_size: 20  # GB
vm_storage: local-lvm
vm_os_template: "{{ lookup('env', 'VM_TEMPLATE') | default('local:vztmpl/ubuntu-24.04-standard_24.04-2_amd64.tar.zst') }}"

# Network Configuration  
vm_network_bridge: vmbr0
vm_swap: 512  # MB
vm_unprivileged: true

# Application Configuration
app_name: db-test
app_user: appuser
app_dir: /opt/db-test
app_service_name: db-test
app_port: 5432

# Service type (concrete to avoid templating recursion)
service_type: database

# Local source code path
local_app_path: "../../services/db-test"

# Production Environment Variables (apps can ignore if not needed)
production_env:
  NODE_ENV: production
  PORT: "5432"
  HOST: "0.0.0.0"

# Security Configuration
ssh_public_key_path: "{{ ansible_env.HOME }}/.ssh/id_proxmox.pub"
allowed_ports:
  - "22"    # SSH
  - "5432"  # DB port
  - "80"
  - "443"

# DNS Configuration for service hostname resolution
dns_server: "192.168.1.11"
dns_domain: "proxmox.local"
service_hostname: "db-test"

# Database-specific values are injected by the generator/update script if not present
# db_type: postgresql
# db_name: {{ db_name | default(service_name) }}
# db_user: {{ db_user | default(service_name) }}
# db_password: "<generated-or-provided>"

runtime_variant: postgresql
db_type: postgresql
db_name: dbtest
db_user: dbuser
db_password: "ov9qBtpl+UMZYfGbLrqUeI8Y6a8T56Ty74QtrDVi4Mw="
