# Tor-Proxy Service Type Configuration
service_type: tor-proxy
runtime_name: "Tor + Privoxy"

# Template parts provided by this service type
provides_runtime_install: true
provides_dependency_install: true
provides_build_tasks: false
provides_systemd_service: false

# File exclusions (no app source)
file_exclusions:
  - ".git"
  - "deployment"
  - "deployments"
  - "*.log"
  - ".env"

# Default environment variables
default_env:
  TOR_SOCKS_PORT: "{{ app_port }}"
  HTTP_PROXY_PORT: "{{ http_proxy_port | default('8118') }}"

# Health check path (unused; we port-check instead)
health_check_path: "/"


