# Service configuration for service01
# Generated on Fri Aug 22 19:01:07 CEST 2025

service_name: service01
service_type: nodejs
runtime_variant: bun
vm_name: service01
vm_id: 201
vm_cores: 2
vm_memory: 2048
vm_disk_size: 20
vm_storage: local-lvm
vm_network_bridge: vmbr0
vm_swap: 512
vm_unprivileged: true

app_name: service01
app_user: appuser
app_dir: /opt/service01
app_service_name: service01
app_port: 3001
app_main_file: index.js
local_app_path: "../../services/service01"

service_hostname: service01
app_subdomain: 

dns_server: 192.168.1.11
dns_domain: proxmox.local

# Proxmox node override (leave empty to use global default)
# proxmox_node: pve2

# Service type specific configuration
nodejs_runtime: bun

# Custom environment variables
custom_env_vars: {}

# Additional ports to open in firewall
additional_ports: []
