# Database Service Type Configuration
service_type: database
runtime_name: "Database"

# Template parts provided by this service type
provides_runtime_install: true
provides_dependency_install: true
provides_build_tasks: false
provides_systemd_service: false

# File exclusions (databases don't typically have source code)
file_exclusions:
  - ".git"
  - "deployment"
  - "deployments"
  - "*.log"
  - ".env"

# Default environment variables
default_env:
  DB_HOST: "0.0.0.0"
  DB_NAME: "{{ db_name | default(service_name) }}"
  DB_USER: "{{ db_user | default(service_name) }}"

# Health check (database-specific)
health_check_path: "/"  # Databases use port checks instead
